In [1]:
import numpy as np


In [21]:
a = np.ones((5)) * 4

In [22]:
a

array([ 4.,  4.,  4.,  4.,  4.])

In [23]:
b = np.array([1,0,0,0,1], dtype=bool)

In [24]:
a[b] = np.array([10,100])

In [25]:
a

array([  10.,    4.,    4.,    4.,  100.])

In [133]:
import tensorflow as tf

In [27]:
np.random.choice([range(4)])

ValueError: a must be 1-dimensional

In [289]:
from importlib import reload

In [290]:
import Estimator_Cliff_Walk; reload(Estimator_Cliff_Walk)

from Estimator_Cliff_Walk import Estimator


In [291]:
tf.reset_default_graph()

estimator = Estimator(4, 48, 64)

(?, 2)


In [292]:
estimator.predict_q_values(np.array([1,2,1,0,2]))

array([[-0.08800407, -0.19444123, -0.08990319,  0.1238998 ],
       [ 0.02026697,  0.10720573,  0.05688876,  0.04298364],
       [-0.08800407, -0.19444123, -0.08990319,  0.1238998 ],
       [-0.08701703, -0.15891911, -0.04454944,  0.02644026],
       [ 0.02026697,  0.10720573,  0.05688876,  0.04298364]], dtype=float32)

In [293]:
estimator.choose_greedy_action(np.array([1,2,1,3,4,2]))

array([3, 1, 3, 3, 3, 1])

In [294]:
estimator.choose_e_greedy_action(np.array([1,2,1,3,4,2]),epsilon=0.5)

array([3, 2, 2, 3, 3, 1])

In [295]:
estimator.update(np.array([2]), np.array([2]), np.array([2]))

3.775681

In [272]:
tf.InteractiveSession()
a= tf.Variable([
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]
])
b = tf.Variable([
   [0,0],
   [1,2] 
])
init = tf.global_variables_initializer()
init.run()


In [277]:
c = tf.gather_nd(a,b)

In [278]:
c.eval()

array([1, 3], dtype=int32)