## am happy now with the parallel envs lets go to implementing q - learning 

In [1]:
from importlib import reload

In [2]:
import ParallelEnvironment; reload(ParallelEnvironment)
import Worker; reload(Worker)


<module 'Worker' from '/home/jaidmin/PycharmProjects/ParallelEnvironment/Worker.py'>

In [3]:
from ParallelEnvironment import *
from Worker import *
from lib.envs.cliff_walking import *

In [4]:
from Environment import Environment

In [5]:
env = CliffWalkingEnv()

In [6]:
class Provider():
    def create(self):
        env = Environment(CliffWalkingEnv(),0,False)
        return env

In [7]:
provider = Provider()

In [8]:

parallel = ParallelEnvironment(provider,4,2,4)

In [9]:
states, rewards,done, actions = parallel.get_shared_variables()

In [10]:
parallel.reset()

array([36, 36, 36, 36], dtype=uint32)

In [11]:
for env in parallel.envs:
    env.render()

o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  o  o
x  C  C  C  C  C  C  C  C  C  C  T

o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  o  o
x  C  C  C  C  C  C  C  C  C  C  T

o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  o  o
x  C  C  C  C  C  C  C  C  C  C  T

o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  o  o
x  C  C  C  C  C  C  C  C  C  C  T



In [13]:
actions.shape

(4, 4)

In [14]:
not_shared_actions = np.zeros((parallel.num_envs,parallel.num_actions))

In [17]:
provider = Provider()
parallel = ParallelEnvironment(provider,4,2,4)
states, rewards,done, actions = parallel.get_shared_variables()
print(states)
for i in range(parallel.num_envs):
    not_shared_actions[i] = np.eye(4)[1]
parallel.step(not_shared_actions)
print(actions)

print(states)
print(rewards)
print(done)
for i in range(parallel.num_envs):
    not_shared_actions[i] = np.eye(4)[3]
parallel.step(not_shared_actions)
print(actions)
print(states)
print(rewards)
print(done)

for i in range(parallel.num_envs):
    not_shared_actions[i] = np.eye(4)[i]
parallel.step(not_shared_actions)
print(actions)
print(states)
print(rewards)
print(done)


    

[36 36 36 36]
[[ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]]
[36 36 36 36]
[-100. -100. -100. -100.]
[ 1.  1.  1.  1.]
[[ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]]
[36 36 36 36]
[-1. -1. -1. -1.]
[ 0.  0.  0.  0.]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[24 36 36 36]
[  -1. -100.   -1.   -1.]
[ 0.  1.  0.  0.]


In [23]:
env = CliffWalkingEnv()

In [24]:
env.reset()

36

In [25]:
env.step(1)

(37, -100.0, True, {'prob': 1.0})

In [20]:
env.step(0)

(12, -1.0, False, {'prob': 1.0})